"""
Agent Memory Stream

Inspired by Stanford Generative Agents (Smallville paper).
Each agent maintains a memory stream of observations that can be reflected upon.

Memory architecture:
- Observations: Raw events the agent experienced
- Reflections: Higher-level insights synthesized from observations
- Scratch: Short-term working memory (current task, recent context)
- Retrieval: Memories retrieved based on recency + importance + relevance
"""
from dataclasses import dataclass, field
from datetime import datetime
from typing import List, Optional, Dict, Any
from enum import Enum
import json
import math


class MemoryType(Enum):
    """Type of memory"""
    OBSERVATION = "observation"  # Raw event
    REFLECTION = "reflection"    # Synthesized insight
    PLAN = "plan"                # Agent's plan/intention


@dataclass
class Observation:
    """
    A single observation in the agent's memory stream.

    Similar to the Stanford paper's event memory.
    """
    id: str
    agent_id: str
    content: str              # What happened
    memory_type: MemoryType
    timestamp: datetime
    importance: float         # 1-10 scale (how important is this?)
    location: Optional[str]   # Where it happened (zone name)
    related_agents: List[str] # Other agents involved
    metadata: Dict[str, Any]  # Additional context
    access_count: int = 0     # How many times retrieved (for recency scoring)
    last_accessed: Optional[datetime] = None

    def __post_init__(self):
        if not self.last_accessed:
            self.last_accessed = self.timestamp

    def to_dict(self) -> Dict[str, Any]:
        """Serialize for storage"""
        return {
            "id": self.id,
            "agent_id": self.agent_id,
            "content": self.content,
            "memory_type": self.memory_type.value,
            "timestamp": self.timestamp.isoformat(),
            "importance": self.importance,
            "location": self.location,
            "related_agents": self.related_agents,
            "metadata": self.metadata,
            "access_count": self.access_count,
            "last_accessed": self.last_accessed.isoformat() if self.last_accessed else None,
        }

    @classmethod
    def from_dict(cls, data: Dict[str, Any]) -> "Observation":
        """Deserialize from storage"""
        return cls(
            id=data["id"],
            agent_id=data["agent_id"],
            content=data["content"],
            memory_type=MemoryType(data["memory_type"]),
            timestamp=datetime.fromisoformat(data["timestamp"]),
            importance=data["importance"],
            location=data.get("location"),
            related_agents=data.get("related_agents", []),
            metadata=data.get("metadata", {}),
            access_count=data.get("access_count", 0),
            last_accessed=datetime.fromisoformat(data["last_accessed"]) if data.get("last_accessed") else None,
        )


@dataclass
class Reflection:
    """
    A higher-level insight synthesized from multiple observations.

    Generated by asking the agent to reflect on recent memories.
    """
    id: str
    agent_id: str
    insight: str              # The reflection text
    source_observations: List[str]  # IDs of observations that led to this
    timestamp: datetime
    importance: float

    def to_dict(self) -> Dict[str, Any]:
        return {
            "id": self.id,
            "agent_id": self.agent_id,
            "insight": self.insight,
            "source_observations": self.source_observations,
            "timestamp": self.timestamp.isoformat(),
            "importance": self.importance,
        }


@dataclass
class Scratch:
    """
    Short-term working memory.

    Current task, immediate context, temporary state.
    """
    current_task: Optional[str] = None
    current_location: str = "tavern"
    recent_context: List[str] = field(default_factory=list)
    working_notes: Dict[str, Any] = field(default_factory=dict)
    attention_bandwidth: int = 5  # How many nearby events to perceive


class AgentMemory:
    """
    Memory stream for a single agent.

    Inspired by Stanford Generative Agents architecture:
    - Observations accumulate over time
    - Reflections are generated periodically
    - Retrieval combines recency, importance, and relevance
    """

    def __init__(self, agent_id: str, reflection_threshold: int = 100):
        """
        Args:
            agent_id: Unique identifier for this agent
            reflection_threshold: Total importance before triggering reflection
        """
        self.agent_id = agent_id
        self.observations: List[Observation] = []
        self.reflections: List[Reflection] = []
        self.scratch = Scratch()
        self.reflection_threshold = reflection_threshold
        self._importance_since_last_reflection = 0

    def add_observation(
        self,
        content: str,
        importance: float,
        location: Optional[str] = None,
        related_agents: List[str] = None,
        metadata: Dict[str, Any] = None,
    ) -> Observation:
        """
        Add a new observation to memory stream.

        Args:
            content: What happened
            importance: 1-10 scale (how important is this?)
            location: Where it happened
            related_agents: Other agents involved
            metadata: Additional context

        Returns:
            The created Observation
        """
        obs = Observation(
            id=f"obs_{self.agent_id}_{len(self.observations)}",
            agent_id=self.agent_id,
            content=content,
            memory_type=MemoryType.OBSERVATION,
            timestamp=datetime.now(),
            importance=importance,
            location=location or self.scratch.current_location,
            related_agents=related_agents or [],
            metadata=metadata or {},
        )

        self.observations.append(obs)
        self._importance_since_last_reflection += importance

        # Check if we should reflect
        if self._importance_since_last_reflection >= self.reflection_threshold:
            self._trigger_reflection_needed()

        return obs

    def retrieve(
        self,
        query: str,
        k: int = 5,
        recency_weight: float = 1.0,
        importance_weight: float = 1.0,
        relevance_weight: float = 1.0,
    ) -> List[Observation]:
        """
        Retrieve k most relevant memories.

        Scoring function from Stanford paper:
            score = α·recency + β·importance + γ·relevance

        Args:
            query: What to retrieve memories about
            k: Number of memories to return
            recency_weight: α weight for recency
            importance_weight: β weight for importance
            relevance_weight: γ weight for relevance

        Returns:
            List of k most relevant observations
        """
        if not self.observations:
            return []

        now = datetime.now()
        scored_observations = []

        for obs in self.observations:
            # Recency: exponential decay (1.0 at t=0, 0.99 at t=1hr, etc.)
            hours_ago = (now - obs.timestamp).total_seconds() / 3600
            recency_score = math.exp(-0.01 * hours_ago)

            # Importance: normalized 0-1 (already 1-10, divide by 10)
            importance_score = obs.importance / 10.0

            # Relevance: simple keyword matching (TODO: use embeddings)
            relevance_score = self._compute_relevance(query, obs.content)

            # Combined score
            score = (
                recency_weight * recency_score +
                importance_weight * importance_score +
                relevance_weight * relevance_score
            )

            scored_observations.append((score, obs))

        # Sort by score and return top k
        scored_observations.sort(key=lambda x: x[0], reverse=True)
        top_k = [obs for _, obs in scored_observations[:k]]

        # Update access tracking
        for obs in top_k:
            obs.access_count += 1
            obs.last_accessed = now

        return top_k

    def _compute_relevance(self, query: str, content: str) -> float:
        """
        Compute relevance score (0-1) between query and content.

        Simple keyword matching for now. In production, use:
        - Embeddings similarity (cosine similarity)
        - Semantic search with vector DB
        """
        query_words = set(query.lower().split())
        content_words = set(content.lower().split())

        if not query_words:
            return 0.0

        # Jaccard similarity
        intersection = query_words & content_words
        union = query_words | content_words
        return len(intersection) / len(union) if union else 0.0

    def _trigger_reflection_needed(self):
        """Mark that agent should reflect on recent memories"""
        # In full implementation, this would:
        # 1. Call LLM to generate reflections from recent observations
        # 2. Store reflections as new observations (with high importance)
        # 3. Reset importance counter
        self._importance_since_last_reflection = 0

    def reflect(self, llm_client=None) -> Optional[Reflection]:
        """
        Generate a reflection from recent observations.

        This would call an LLM with a prompt like:
        "Given these recent memories, what are 3 high-level insights?"

        For now, returns None (not implemented yet).
        TODO: Integrate with Gemini Flash for cheap reflections
        """
        # Get recent high-importance observations
        recent = sorted(
            [obs for obs in self.observations if obs.memory_type == MemoryType.OBSERVATION],
            key=lambda x: x.timestamp,
            reverse=True
        )[:10]

        if not recent or not llm_client:
            return None

        # TODO: Call LLM to generate reflection
        # reflection_text = llm_client.generate_reflection(recent)
        # reflection = Reflection(...)
        # self.reflections.append(reflection)

        return None

    def get_recent_memories(self, count: int = 10) -> List[Observation]:
        """Get the most recent memories"""
        return sorted(self.observations, key=lambda x: x.timestamp, reverse=True)[:count]

    def get_memories_about(self, topic: str, count: int = 5) -> List[Observation]:
        """Get memories related to a topic"""
        return self.retrieve(query=topic, k=count)

    def update_scratch(self, **kwargs):
        """Update short-term working memory"""
        for key, value in kwargs.items():
            if hasattr(self.scratch, key):
                setattr(self.scratch, key, value)

    def save(self, filepath: str):
        """Save memory to JSON file"""
        data = {
            "agent_id": self.agent_id,
            "observations": [obs.to_dict() for obs in self.observations],
            "reflections": [refl.to_dict() for refl in self.reflections],
            "scratch": {
                "current_task": self.scratch.current_task,
                "current_location": self.scratch.current_location,
                "recent_context": self.scratch.recent_context,
                "working_notes": self.scratch.working_notes,
            },
        }
        with open(filepath, 'w') as f:
            json.dump(data, f, indent=2)

    @classmethod
    def load(cls, filepath: str) -> "AgentMemory":
        """Load memory from JSON file"""
        with open(filepath, 'r') as f:
            data = json.load(f)

        memory = cls(agent_id=data["agent_id"])
        memory.observations = [Observation.from_dict(obs) for obs in data["observations"]]
        memory.reflections = [
            Reflection(
                id=refl["id"],
                agent_id=refl["agent_id"],
                insight=refl["insight"],
                source_observations=refl["source_observations"],
                timestamp=datetime.fromisoformat(refl["timestamp"]),
                importance=refl["importance"],
            )
            for refl in data["reflections"]
        ]
        memory.scratch.current_task = data["scratch"].get("current_task")
        memory.scratch.current_location = data["scratch"].get("current_location", "tavern")
        memory.scratch.recent_context = data["scratch"].get("recent_context", [])
        memory.scratch.working_notes = data["scratch"].get("working_notes", {})

        return memory

    def get_context_summary(self, max_tokens: int = 500) -> str:
        """
        Generate a summary of agent's memory for inclusion in prompt.

        Returns a concise summary of:
        - Current task
        - Recent important memories
        - Relevant reflections
        """
        summary_parts = []

        if self.scratch.current_task:
            summary_parts.append(f"Current task: {self.scratch.current_task}")

        recent_memories = self.get_recent_memories(count=5)
        if recent_memories:
            summary_parts.append("\nRecent experiences:")
            for mem in recent_memories:
                summary_parts.append(f"- {mem.content}")

        if self.reflections:
            summary_parts.append("\nKey insights:")
            for refl in self.reflections[-3:]:  # Last 3 reflections
                summary_parts.append(f"- {refl.insight}")

        return "\n".join(summary_parts)


# Example usage:
"""
# In agent initialization:
memory = AgentMemory(agent_id="rogue")

# During quest execution:
memory.add_observation(
    content="Implemented JWT token validation in src/auth.rs",
    importance=8,
    location="forge",
    metadata={"files_changed": ["src/auth.rs"]}
)

memory.add_observation(
    content="Tank reported 3 test failures in auth module",
    importance=9,
    location="arena",
    related_agents=["tank"],
)

# When building agent prompt:
relevant_memories = memory.retrieve(
    query="authentication implementation",
    k=5
)

context = memory.get_context_summary()
# Include this context in agent's system prompt

# At end of quest:
memory.save(f"quests/quest_123/memories/{memory.agent_id}.json")
"""
